### ISSUE TITLE
The cron is not running in docker.

### ISSUE THREAD

**Issue by ekmayen** [safatshahin/moodle-docker#1]
Hi,
I have created two containers one with ssl and one without ssl and in both cases the cron stop working.
I also purged the caches in moodle, docker and browser but the last run of the cron was one week ago.

Could you please help me with this? 
Docker version 20.10.2, build 2291f61
Moodle 3.10

**Comment by safatshahin** [comment]
Hi @ekmayen 
I have investigated the non ssl one, its working perfect, can you please check the cronlog getting into your shell of the docker?

**Comment by ekmayen** [comment]
Hi @safatshahin,

I have re-tested the cron and it is working as expected. I am not sure what the issue was. Thank you for verifying this.
